# Active Profile
spring.profiles.active=@spring.profiles.active@

# Application Name
spring.application.name=razorpay-provider-service

# Server Configuration
server.port=8083

# Razorpay Configuration
razorpay.client-name=razorpay-client
razorpay.base-url=https://api.razorpay.com

# Logging Configuration
logging.level.com.paybridge.payments.client=INFO

# HTTP Client Connection Pool Configuration
http.pool.max-total=200
http.pool.max-per-route=50

# Instructs Feign to look for your HttpClient 5 Bean config
spring.cloud.openfeign.httpclient.hc5.enabled=true

# Jackson Configuration
spring.jackson.serialization.write-dates-as-timestamps=false

# Internationalization Configuration
spring.messages.basename=error-messages
