# Active Profile
spring.profiles.active=@spring.profiles.active@

# Application Name
spring.application.name=razorpay-provider-service

# Server Configuration
server.port=8080

# Razorpay Configuration
razorpay.client-name=razorpay-client
razorpay.base-url=https://api.razorpay.com

# Logging Configuration
logging.level.com.paybridge.payments.client=INFO

# HTTP Client Connection Pool Configuration
http.pool.max-total=200
http.pool.max-per-route=50

# Instructs Feign to look for your HttpClient 5 Bean config
spring.cloud.openfeign.httpclient.hc5.enabled=true

# Jackson Configuration
spring.jackson.serialization.write-dates-as-timestamps=false

# Internationalization Configuration
spring.messages.basename=error-messages

# ===== Retry =====
resilience4j.retry.instances.razorpay.max-attempts=3
resilience4j.retry.instances.razorpay.wait-duration=500ms
resilience4j.retry.instances.razorpay.retry-exceptions=java.net.ConnectException,feign.RetryableException,java.net.UnknownHostException
resilience4j.retry.instances.razorpay.ignore-exceptions=com.paybridge.payments.exception.RazorpayProviderException

# ===== Circuit Breaker =====
resilience4j.circuitbreaker.instances.razorpay.sliding-window-type=count_based
resilience4j.circuitbreaker.instances.razorpay.sliding-window-size=10
resilience4j.circuitbreaker.instances.razorpay.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.razorpay.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.razorpay.wait-duration-in-open-state=30s
resilience4j.circuitbreaker.instances.razorpay.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.razorpay.automatic-transition-from-open-to-half-open-enabled=true
